default: &default
  adapter: mysql2
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: whereIsTheWater_development

test:
  <<: *default
  database: whereIsTheWater_test

production:
  <<: *default
  database: nfyqgqch
  username: nfyqgqch
  password: CqZZz4sYIv6_OHR-wxS95zy04hLTdRrf
